services:
  - type: web
    name: mazeej
    env: node
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
