services:
  - type: web
    name: mazeej-backend
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm ci && npm run build:render
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
